## Deep Learning Model - CNN Multi-Label Text Classification
### Universal Sentence Encoder with Sub Themes (Right Now Ran for Main Themes)

In [1]:
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers import Conv1D, Conv2D, MaxPooling2D, GlobalMaxPooling1D, MaxPool1D, MaxPooling1D
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding, LSTM
from keras.utils import to_categorical
from tensorflow.keras import layers
from keras import backend as K


import pandas as pd
import numpy as np
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
import spacy
# from collections import Counter
import en_core_web_sm
nlp = en_core_web_sm.load()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

Using plaidml.keras.backend backend.


### Loading Data

In [2]:
X_train_Q1 = pd.read_excel('../data/interim/X_train_Q1_clean.xlsx')
X_valid_Q1 = pd.read_excel('../data/interim/X_valid_Q1_clean.xlsx')

y_train_Q1 = pd.read_excel('../data/interim/y_train_Q1.xlsx')
y_valid_Q1 = pd.read_excel('../data/interim/y_valid_Q1.xlsx')

### Creating a Unified Dataframe for CNN Ready Model

In [3]:
df = pd.concat([X_train_Q1, y_train_Q1.iloc[:,0:12]], axis = 1)

In [4]:
df.head()

Comment  CPD  CB  EWC  Exec  FEW  \
0  to be real about diversity, you need to create...    0   0    1     0    0   
1  Keep the building warmer and provide warm wate...    0   0    0     0    0   
2             better communication from the top down    0   0    0     1    0   
3  It would be beneficial if Management did not m...    0   0    0     0    0   
4                more education applicable to my job    1   0    0     0    0   

   SP  RE  Sup  SW  TEPE  VMG  OTH  
0   0   0    0   0     0    0    0  
1   0   0    0   0     1    0    0  
2   0   0    0   0     0    0    0  
3   0   1    0   0     0    0    0  
4   0   0    0   0     0    0    0

In [5]:
data_df = df

In [6]:
data_df.shape

(10376, 13)

### Pre-processing

#### General

In [7]:
import re

def decontracted(phrase):
    # specific
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [8]:
stopwords= set(['br', 'the', 'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves',\
            "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', \
            'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their',\
            'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', \
            'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', \
            'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', \
            'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',\
            'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further',\
            'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more',\
            'most', 'other', 'some', 'such', 'only', 'own', 'same', 'so', 'than', 'too', 'very', \
            's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', \
            've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn',\
            "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn',\
            "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", \
            'won', "won't", 'wouldn', "wouldn't"])

In [9]:
from tqdm import tqdm
preprocessed_synopsis = []
# tqdm is for printing the status bar
for sentance in data_df['Comment'].values:
    sentance = re.sub(r"http\S+", "", sentance)
    sentance = BeautifulSoup(sentance, 'lxml').get_text()
    sentance = decontracted(sentance)
    sentance = re.sub("\S*\d\S*", "", sentance).strip()
    sentance = re.sub('[^A-Za-z]+', ' ', sentance)
    # https://gist.github.com/sebleier/554280
    sentance = ' '.join(e.lower() for e in sentance.split() if e.lower() not in stopwords)
    preprocessed_synopsis.append(sentance.strip())
data_df['preprocessed_comments']=preprocessed_synopsis

In [10]:
data_df.head()

Comment  CPD  CB  EWC  Exec  FEW  \
0  to be real about diversity, you need to create...    0   0    1     0    0   
1  Keep the building warmer and provide warm wate...    0   0    0     0    0   
2             better communication from the top down    0   0    0     1    0   
3  It would be beneficial if Management did not m...    0   0    0     0    0   
4                more education applicable to my job    1   0    0     0    0   

   SP  RE  Sup  SW  TEPE  VMG  OTH  \
0   0   0    0   0     0    0    0   
1   0   0    0   0     1    0    0   
2   0   0    0   0     0    0    0   
3   0   1    0   0     0    0    0   
4   0   0    0   0     0    0    0   

                               preprocessed_comments  
0  real diversity you need create seats table mea...  
1   keep building warmer provide warm water bathroom  
2                           better communication top  
3       would beneficial management not micro manage  
4                           education applicable job

#### Our Pre-processor

In [ ]:
def preprocess_comments(text, 
                        min_token_len = 2, 
                        irrelevant_pos = ['PRON', 'SPACE', 'PUNCT', 'ADV', 
                                          'ADP', 'CCONJ', 'AUX', 'PRP'],
                        avoid_entities = ['PERSON', 'ORG', 'LOC', 'GPE']):
# note: Didn't use the following options in the `preprocess_comments`...
#    - 'PROPN' because it erases proper names as 'George', but also words as orange.
#    - 'DET' since it removes the word 'no', which changes the meaning of a sentence.
# *for more information see link: https://universaldependencies.org/u/pos/
    """
    Given text, min_token_len, irrelevant_pos and avoid_entities, carries out 
    preprocessing of the text and returns list of preprocessed text. 
    
    Parameters
    -------------
    text : (list) 
        the list of text to be preprocessed
    min_token_len : (int) 
        min_token_length required
    irrelevant_pos : (list) 
        a list of irrelevant pos tags
    avoid_entities : (list)
        a list of entity labels to be avoided
    
    Returns
    -------------
    (list) list of preprocessed text
    
    Example
    -------------
    >>> example = ["Hello, I'm George and I love swimming!",
                   "I am a really good cook; what about you?",
                   "Contact me at george23@gmail.com"]

    >>> preprocess(example)
    (output:) ['hello love swimming', 'good cook', 'contact']
    """

    result = []
    
    others = ["'s", "the", "that", "this", "to", "-PRON-"]
    # I add "-PRON-" that erase "my", "your", etc. other way to erase them is to
    #   use adding 'DET' to irrelevant_pos but it would erase the word 'no' too.
    
    for sent in text:
        sent = sent.lower()
        sent = re.sub(r"facebook", "social media", sent)
        sent = re.sub(r"twitter", "social media", sent)
        sent = re.sub(r"instagram", "social media", sent)
        sent = re.sub(r"whatsapp", "social media", sent)
        sent = re.sub(r"linkedin", "social media", sent)
        sent = re.sub(r"snapchat", "social media", sent)
        
        result_sent = []
        doc = nlp(sent)
        entities = [str(ent) for ent in doc.ents if ent.label_ in avoid_entities]
        # This helps to detect names of persons, organization and dates
        
        for token in doc:            
            if (token.like_email or
                token.like_url or
                token.pos_ in irrelevant_pos or
                str(token) in entities or
                str(token.lemma_) in others or
                len(token) < min_token_len):
                continue
            else:
                result_sent.append(token.lemma_)
        result.append(" ".join(result_sent))
    return result

In [ ]:
data_df['preprocessed_comments']=preprocess_comments(data_df['Comment'])

In [ ]:
data_df.head()

### Splitting into Train and Test

In [11]:
data_df.head()

Comment  CPD  CB  EWC  Exec  FEW  \
0  to be real about diversity, you need to create...    0   0    1     0    0   
1  Keep the building warmer and provide warm wate...    0   0    0     0    0   
2             better communication from the top down    0   0    0     1    0   
3  It would be beneficial if Management did not m...    0   0    0     0    0   
4                more education applicable to my job    1   0    0     0    0   

   SP  RE  Sup  SW  TEPE  VMG  OTH  \
0   0   0    0   0     0    0    0   
1   0   0    0   0     1    0    0   
2   0   0    0   0     0    0    0   
3   0   1    0   0     0    0    0   
4   0   0    0   0     0    0    0   

                               preprocessed_comments  
0  real diversity you need create seats table mea...  
1   keep building warmer provide warm water bathroom  
2                           better communication top  
3       would beneficial management not micro manage  
4                           education applicable job

In [12]:
X_train = data_df[['preprocessed_comments']]
y_train = data_df.drop(['Comment', 'preprocessed_comments'], axis=1)

In [ ]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

### Preparing Labels

**Max length of sentence**

In [13]:
def max_len(x):
    a=x.split()
    return len(a)

max_len = max(data_df['Comment'].apply(max_len))
max_len

150

### Vocab Size

In [14]:
vect=Tokenizer()
vect.fit_on_texts(X_train['preprocessed_comments'])
vocab_size = len(vect.word_index) + 1
print(vocab_size)

11919


**Universal Sentence Encoder**

In [15]:
import tensorflow as tf
import tensorflow_hub as hub
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")

In [16]:
embeddings = embed(X_train['preprocessed_comments'])

In [17]:
embedding_matrix = np.array(embeddings)

In [18]:
embedding_matrix

array([[-0.03669859, -0.07417478,  0.03231422, ...,  0.01621998,
         0.00728293,  0.00265464],
       [ 0.05218186, -0.01258108, -0.04657765, ...,  0.05539099,
         0.05895472, -0.0171202 ],
       [-0.01777638, -0.04568463,  0.00473103, ..., -0.00073464,
        -0.08261821,  0.05859691],
       ...,
       [ 0.03823395,  0.01441879,  0.06019125, ...,  0.06164353,
        -0.02452262, -0.01176131],
       [-0.03514517, -0.04318713, -0.02938136, ...,  0.0648592 ,
        -0.05883494,  0.01129983],
       [ 0.02614759, -0.05074428,  0.00971   , ...,  0.01864268,
         0.05439513,  0.03895477]], dtype=float32)

In [19]:
embedding_matrix.shape

(10376, 512)

## Modelling CNN

#### Padding to make all sequences of same length

**Training Data**

In [20]:
encoded_docs_train = vect.texts_to_sequences(X_train['preprocessed_comments'])
max_length = vocab_size
padded_docs_train = pad_sequences(encoded_docs_train, maxlen=max_len, padding='post')
print(padded_docs_train)

[[  504   585    36 ...     0     0     0]
 [  134    54  3393 ...     0     0     0]
 [    7    29   234 ...     0     0     0]
 ...
 [  697     4    12 ...     0     0     0]
 [  476  2745 11917 ...     0     0     0]
 [ 1147   593   791 ...     0     0     0]]


In [21]:
padded_docs_train.shape

(10376, 150)

#### Defining Model

## Universal Sentence Encoder

In [ ]:
y_train = np.array(y_train)

max_features = embedding_matrix.shape[0]
maxlen = max_len
batch_size = 128
filters = 250
kernel_size = 3
hidden_dims = 250
epochs = 1
embed_size = 512 # for universal sentence encoder
n_class = 12

In [ ]:
model = Sequential()

model.add(Embedding(max_features, embed_size, weights=[embedding_matrix],
                        trainable=False, input_length=maxlen))




model.add(Dropout(0.2))
model.add(Conv1D(filters, kernel_size, padding='valid', activation='relu',
                 strides=1))
model.add(MaxPooling1D())
model.add(Conv1D(filters, kernel_size, padding='valid',activation='relu'))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(hidden_dims, activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(n_class, activation = 'sigmoid'))


model.summary()

In [ ]:
padded_docs_train.shape

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

# Train Model
model.fit(padded_docs_train, y_train, batch_size=batch_size, epochs=epochs,
          validation_split=0.05)

## New Model Testing begins

In [23]:
y_train = np.array(y_train)

In [65]:
max_features = embedding_matrix.shape[0]
maxlen = max_len
batch_size = 128
filters = 250
kernel_size = 3
hidden_dims = 250
epochs = 1
embed_size = 512 # for universal sentence encoder
n_class = 12

In [66]:
model = Sequential()
model.add(Embedding(vocab_size, embed_size, input_length=embed_size))
#model.add(Conv1D(filters, kernel_size, padding='valid', activation='relu',strides=1))
model.add(GlobalMaxPooling1D())
#model.add(Dense(hidden_dims, activation = 'relu'))
#model.add(Dropout(0.6))
model.add(Dense(n_class, activation = 'sigmoid'))


model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 512, 512)          6102528   
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 512)               0         
_________________________________________________________________
dense_18 (Dense)             (None, 12)                6156      
Total params: 6,108,684
Trainable params: 6,108,684
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

model.fit(embedding_matrix, y_train, batch_size=batch_size, epochs=epochs,
          validation_split=0.15)

Train on 8819 samples, validate on 1557 samples
Epoch 1/1


### Testing Simple Keras Model

In [49]:
max_features = embedding_matrix.shape[0]
maxlen = max_len
batch_size = 150
filters = 250
kernel_size = 3
hidden_dims = 250
epochs = 10
embed_size = 512 # for universal sentence encoder
n_class = 12

In [60]:
model = Sequential()

model.add(Dense(max_features, input_shape=(512,)))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(Activation('relu'))
model.add(Dropout(0.1))
model.add(Activation('relu'))
#model.add(Dropout(0.1))
model.add(Dense(n_class))
model.add(Activation('sigmoid'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 10376)             5322888   
_________________________________________________________________
activation_23 (Activation)   (None, 10376)             0         
_________________________________________________________________
dropout_15 (Dropout)         (None, 10376)             0         
_________________________________________________________________
activation_24 (Activation)   (None, 10376)             0         
_________________________________________________________________
dropout_16 (Dropout)         (None, 10376)             0         
_________________________________________________________________
activation_25 (Activation)   (None, 10376)             0         
_________________________________________________________________
dense_17 (Dense)             (None, 12)                124524    
__________

In [61]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

model.fit(embedding_matrix, y_train, batch_size=batch_size, epochs=epochs,
          validation_split=0.15)

Train on 8819 samples, validate on 1557 samples
Epoch 1/10
8819/8819 [==============================] - 3s 352us/step - loss: 0.2990 - acc: 0.8945 - val_loss: 0.2108 - val_acc: 0.9231
Epoch 2/10
8819/8819 [==============================] - 2s 181us/step - loss: 0.1971 - acc: 0.9254 - val_loss: 0.1965 - val_acc: 0.9274
Epoch 3/10
8819/8819 [==============================] - 2s 175us/step - loss: 0.1824 - acc: 0.9307 - val_loss: 0.1920 - val_acc: 0.9291
Epoch 4/10
8819/8819 [==============================] - 2s 176us/step - loss: 0.1730 - acc: 0.9337 - val_loss: 0.1896 - val_acc: 0.9281
Epoch 5/10
8819/8819 [==============================] - 2s 176us/step - loss: 0.1650 - acc: 0.9362 - val_loss: 0.1880 - val_acc: 0.9291
Epoch 6/10
8819/8819 [==============================] - 2s 177us/step - loss: 0.1565 - acc: 0.9395 - val_loss: 0.1894 - val_acc: 0.9281
Epoch 7/10
8819/8819 [==============================] - 2s 176us/step - loss: 0.1473 - acc: 0.9425 - val_loss: 0.1899 - val_acc: 0.9268


## Evaluation - Validation Set

In [62]:
df_valid = pd.concat([X_valid_Q1, y_valid_Q1.iloc[:,:12]], axis = 1)

# pre-processing test data
from tqdm import tqdm
preprocessed_synopsis = []
# tqdm is for printing the status bar
for sentance in df_valid['Comment'].values:
    sentance = re.sub(r"http\S+", "", sentance)
    sentance = BeautifulSoup(sentance, 'lxml').get_text()
    sentance = decontracted(sentance)
    sentance = re.sub("\S*\d\S*", "", sentance).strip()
    sentance = re.sub('[^A-Za-z]+', ' ', sentance)
    # https://gist.github.com/sebleier/554280
    sentance = ' '.join(e.lower() for e in sentance.split() if e.lower() not in stopwords)
    preprocessed_synopsis.append(sentance.strip())
    
    
df_valid['preprocessed_comments']=preprocessed_synopsis

# creating X and Y
X_valid = df_valid[['preprocessed_comments']]
y_valid = df_valid.drop(columns=['Comment', 'preprocessed_comments'])

y_valid = np.array(y_valid)

# creating embedding for validation
embeddings_valid = embed(X_valid['preprocessed_comments'])
embedding_matrix_valid = np.array(embeddings_valid)

score = model.evaluate(embedding_matrix_valid,y_valid)
score

2594/2594 [==============================] - 3s 1ms/step


[0.18472839403630406, 0.9315407588193301]

## Evaluation - Precision & Recall

In [63]:
pred = model.predict(embedding_matrix_valid, batch_size=batch_size, verbose=1)

2594/2594 [==============================] - 1s 199us/step


In [64]:
from sklearn.metrics import precision_score, recall_score, f1_score

#predictions=model.predict([padded_docs_test])
predictions = pred
thresholds=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

for val in thresholds:
    print("For threshold: ", val)
    pred=predictions.copy()
  
    pred[pred>=val]=1
    pred[pred<val]=0
  
    precision = precision_score(y_valid, pred, average='micro')
    recall = recall_score(y_valid, pred, average='micro')
    f1 = f1_score(y_valid, pred, average='micro')
   
    print("Micro-average quality numbers")
    print("Precision: {:.4f}, Recall: {:.4f}, F1-measure: {:.4f}".format(precision, recall, f1))
    print('\n')

For threshold:  0.1
Micro-average quality numbers
Precision: 0.4625, Recall: 0.8405, F1-measure: 0.5967


For threshold:  0.2
Micro-average quality numbers
Precision: 0.5811, Recall: 0.7532, F1-measure: 0.6561


For threshold:  0.3
Micro-average quality numbers
Precision: 0.6652, Recall: 0.6882, F1-measure: 0.6765


For threshold:  0.4
Micro-average quality numbers
Precision: 0.7252, Recall: 0.6332, F1-measure: 0.6761


For threshold:  0.5
Micro-average quality numbers
Precision: 0.7749, Recall: 0.5793, F1-measure: 0.6630


For threshold:  0.6
Micro-average quality numbers
Precision: 0.8161, Recall: 0.5213, F1-measure: 0.6362


For threshold:  0.7
Micro-average quality numbers
Precision: 0.8603, Recall: 0.4666, F1-measure: 0.6050


For threshold:  0.8
Micro-average quality numbers
Precision: 0.8910, Recall: 0.3930, F1-measure: 0.5455


For threshold:  0.9
Micro-average quality numbers
Precision: 0.9386, Recall: 0.3085, F1-measure: 0.4643




### Testing RNN

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping

In [ ]:
def RNN():
    inputs = Input(name='inputs',shape=[512])
    layer = Embedding(max_features,50,input_length=512)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(12,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [ ]:
model = RNN()

In [ ]:
model.summary()

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

model.fit(embedding_matrix, y_train, batch_size=batch_size, epochs=epochs,
          validation_split=0.05)

## New Model Testing ends

**Score on Validation Data**

In [ ]:
df_valid = pd.concat([X_valid_Q1, y_valid_Q1.iloc[:,:12]], axis = 1)

# pre-processing test data
from tqdm import tqdm
preprocessed_synopsis = []
# tqdm is for printing the status bar
for sentance in df_valid['Comment'].values:
    sentance = re.sub(r"http\S+", "", sentance)
    sentance = BeautifulSoup(sentance, 'lxml').get_text()
    sentance = decontracted(sentance)
    sentance = re.sub("\S*\d\S*", "", sentance).strip()
    sentance = re.sub('[^A-Za-z]+', ' ', sentance)
    # https://gist.github.com/sebleier/554280
    sentance = ' '.join(e.lower() for e in sentance.split() if e.lower() not in stopwords)
    preprocessed_synopsis.append(sentance.strip())
    
    
df_valid['preprocessed_comments']=preprocessed_synopsis

# creating X and Y

X_valid = df_valid[['preprocessed_comments']]
y_valid = df_valid.drop(columns=['Comment', 'preprocessed_comments'])

y_valid = np.array(y_valid)

# creating padded dataset for x_valid
encoded_docs_valid = vect.texts_to_sequences(X_valid['preprocessed_comments'])
padded_docs_valid = pad_sequences(encoded_docs_valid, maxlen=max_len, padding='post')
print(padded_docs_valid)

In [ ]:
score = model.evaluate(padded_docs_valid,y_valid)

In [ ]:
score

## Saving Model

In [ ]:
model.save('../models/cnn_use_sub_themes.pkl')

## Precision & Recall

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score, f1_score

pred = model.predict(padded_docs_valid, batch_size=batch_size, verbose=1)

In [ ]:
#predictions=model.predict([padded_docs_test])
predictions = pred
thresholds=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]

for val in thresholds:
    print("For threshold: ", val)
    pred=predictions.copy()
  
    pred[pred>=val]=1
    pred[pred<val]=0
  
    precision = precision_score(y_valid, pred, average='micro')
    recall = recall_score(y_valid, pred, average='micro')
    f1 = f1_score(y_valid, pred, average='micro')
   
    print("Micro-average quality numbers")
    print("Precision: {:.4f}, Recall: {:.4f}, F1-measure: {:.4f}".format(precision, recall, f1))